# Numpy Fundamentals

In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
# 2D and 3D
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(type(b))
print('----------------------')
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)
print(type(c))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
----------------------
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [13]:
# float data type

np.array([1,2,3], dtype='float')

array([1., 2., 3.])

In [47]:
# np.arange

print(np.arange(1, 10, 2))

np.arange(16).reshape(2,2,2,2)

[1 3 5 7 9]


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [42]:
# np.reshape (to convert the shape)

np.arange(1,13).reshape(3,4)  # 3*4 = 12

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
# np.ones adn np.zeros

print(np.ones((3,4)))
print('------------------')
print(np.zeros((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
# np.random

print(np.random.random(4))
print('---------------------------------------------')
print(np.random.random((3,4)))

[0.39933128 0.41643242 0.34226942 0.92915784]
---------------------------------------------
[[0.75392714 0.22067469 0.5830055  0.78988876]
 [0.73714742 0.81876105 0.45884491 0.64323046]
 [0.79669632 0.27415327 0.14118815 0.49533211]]


In [36]:
# np.linspace.    (linear space) at a given range with equal distance create points

np.linspace(-8,8, 20)

array([-8.        , -7.15789474, -6.31578947, -5.47368421, -4.63157895,
       -3.78947368, -2.94736842, -2.10526316, -1.26315789, -0.42105263,
        0.42105263,  1.26315789,  2.10526316,  2.94736842,  3.78947368,
        4.63157895,  5.47368421,  6.31578947,  7.15789474,  8.        ])

In [37]:
# np.identitiy  matrix where diagonals are 1

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array attributes

In [71]:
a1 = np.arange(10, dtype = np.int32)
a2 = np.arange(12, dtype='float').reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print('\n')
print(a2)

print('\n')

print(a3)


[0 1 2 3 4 5 6 7 8 9]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [72]:
# ndim (dimension)

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [73]:
# shape

print(a1.shape)
print(a2.shape)
print(a3.shape)   # a3.shape (2,2,2)  first 2-> shows how many 2D arrays and second,third 2-> shows no_rows and cols

(10,)
(3, 4)
(2, 2, 2)


In [74]:
# size

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [76]:
# itemsize  (integer, float size)

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [77]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## change datatype

In [82]:
# astype   (used to save the memory space)
a3.astype(dtype = np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array operations

In [90]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print('\n')
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [98]:
# scalar operations

# arthimetic
a1 * 3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [101]:
# relational operators
print(a2)
a2 > 15

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [105]:
# vector operations
# arthimetic

a1 + a2

array([[13, 15, 17, 19],
       [21, 23, 25, 27],
       [29, 31, 33, 35]])

## Array functions

In [109]:
a1 = np.random.random(12).reshape(3,4)
a1

array([[0.11345102, 0.77617254, 0.64473695, 0.51425921],
       [0.36182853, 0.71137181, 0.50854336, 0.27595686],
       [0.21898591, 0.92193807, 0.06107752, 0.47060724]])

In [111]:
a1 = np.round(a1*100)
a1

array([[11., 78., 64., 51.],
       [36., 71., 51., 28.],
       [22., 92.,  6., 47.]])

In [119]:
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))


# row wise max
# 0->columns 1-> row
print(np.max(a1, axis=1))
print(np.min(a1, axis=0))
print(np.prod(a1, axis =1))

92.0
6.0
557.0
[78. 71. 92.]
[11. 71.  6. 28.]
[2800512. 3649968.  570768.]


In [121]:
# mean / median/std/ var

print(np.mean(a1, axis=1))

[51.   46.5  41.75]


In [134]:
# dot
a1 = np.random.random(12).reshape(3,4)
a2 = np.random.random(12).reshape(4,3)

np.dot(a1, a2)

array([[1.47074548, 0.38555131, 1.71144766],
       [0.44200644, 0.63863711, 0.87903036],
       [0.9055124 , 0.94424989, 1.40368823]])

In [135]:
# log
np.log(a1)

array([[-0.16503627, -0.11536431, -1.80325599, -1.3220161 ],
       [-2.35440262, -1.48175115, -0.40316927, -4.48101371],
       [-2.29991142, -0.82724736, -0.02640572, -1.26664994]])

In [137]:
# exp
np.exp(a2)

array([[2.71326983, 1.24152222, 2.31822552],
       [1.39174789, 1.03939843, 2.43025927],
       [1.47750787, 2.48619951, 2.43562227],
       [2.70801478, 1.0683932 , 1.25544701]])

In [144]:
# round/floor/ceil

a = np.random.random((2,3)) * 100
np.ceil(a)

array([[18., 97., 41.],
       [96., 29., 74.]])

## Indexing and Slicing

In [152]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print('\n')
print(a2)
print('\n')

print(a3)

[0 1 2 3 4 5 6 7 8 9]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [163]:
# indexing
a1[-1]

9

In [184]:
print(a2)

# 6 location in a2
print(a2[1,2]) #or
print(a2[1][2])
print(a2[2,3])

print('\n')
print(a3)
print('\n')
print(a3[1][0][1])   # a3[which 2d array][which row][which column]
print(a3[0][0][0])
print(a3[1][1][0]) #or a3[1,1,0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
6
11


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


5
0
6


In [215]:
# slicing

print(a1)

# 2 to 4
print(a1[2:5])
print(a1[2:5:2])
print('\n')
print(a2)
print(a2[0][:])
print(a2[:,2])
print(a2[:,-1])

print(a2[1:, 1:3])
print('\n')
print(a2[::2,::3])
print('\n')
print(a2[::2,1::2])
print('\n')
print(a2[1:, 0::3])
print('\n')
print(a2[0:2, 1:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[ 3  7 11]
[[ 5  6]
 [ 9 10]]


[[ 0  3]
 [ 8 11]]


[[ 1  3]
 [ 9 11]]


[[ 4  7]
 [ 8 11]]


[[1 2 3]
 [5 6 7]]


In [228]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)
print(a3[1])
print('\n')
print(a3[::2])
print(a3[0, 1, :])
print(a3[1, :, 1])
print(a3[2, 1:, 1:])  # a3[which array 1or2or3][which row][which column]
print('\n')
print(a3[0::2, 0, 0::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]


[[ 0  2]
 [18 20]]


## Iterating

In [229]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [235]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [236]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Transpose

In [239]:
print(np.transpose(a2))
a2.T

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## Ravel  (convert in to 1D array)

In [240]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Stacking

In [243]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print('\n')
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [252]:
# horizontal stack
print(np.hstack((a4,a5)))
print('\n')
# vertical stack
print(np.vstack((a4,a5)))


[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Splitting

In [257]:
# horizontal splitting
print(np.hsplit(a4,2))
print('\n')
print(np.vsplit(a5,3))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
